### ISSUE TITLE
Establish and document a pattern for forcing a skipped dependency to reconcile

### ISSUE THREAD

**Issue by ericlarssen** [koreo-dev/koreo-core#21]
Given the following workflow steps, if I always want step2 to reconcile. How do you ensure that?

``` yaml
- label: step1
   ref:
     name: step1
     kind: ValueFunction
   skipIf: =parent.shouldSkip
   inputs:
      thing: value
- label: step2 <- If this should run regardless if step2 is skipped.
   ref:
     name: step2
     kind: ValueFunction
   inputs:
      thing: =steps1.value
```

**Comment by robertkluin** [comment]
I would love feedback on the solution I've been working on for this functionality.

The notion is to improve the structural-type checking to detect handling of potentially missing / non-ok inputs, indicating they're not required. That is, given this input:

```yaml
- label: step2
   inputs:
      thing: "=has(steps.step1.value) ? steps.step1.value : 'value to use if steps.step1 was non-ok'"
```

Provide the default value and allow step2 to evaluate.

An alternative would be to provide a separate key to specify required versus optional inputs, something like this:

```yaml
- label: step2
  optionalSteps:
    step1:
      value:  "value to use if steps.step1 was non-ok"
  inputs:
      thing: =steps.step1.value
```

I have not implemented this approach because 1) I believe the structural typing can be improved to auto-detect this, which would be nicer to use and 2) this could be very verbose, and if you're willing to be this verbose a sub-workflow can accomplish this (and more) today.

I'd love thoughts or other alternative ideas on this.
