### ISSUE TITLE
Add `triggerSchema` to Workflow

### ISSUE THREAD

**Issue by robertkluin** [koreo-dev/koreo-core#23]
In addition to `crdRef`, which specifies a user managed crd to use, add a `triggerSchema` which will allow the user to specify the schema inline. 

```yaml
apiVersion: koreo.dev/v1beta1
kind: Workflow
metadata:
  name: simple-example.v1
  namespace: koreo-demo
spec:
  triggerSchema:
    version: v1beta1
    kind: MyTrigger
    spec:
      name: string
      namespace: string
      image: string

  steps:
    - label: config
      ref:
        kind: ValueFunction
        name: simple-example-config.v1

      inputs:
        name: =parent.name
        namespace: =parent.namespace
        image: =parent.image
```

**Comment by robertkluin** [comment]
Initially I _thought_ a oneOf, yes. Perhaps we should instead add a `schema` property to `crdRef` that defines the `spec` and `status.state` fields?

As I started thinking through a prototype of the schema definition, I found myself debating on embedding a full OpenAPI spec versus something simpler and lighter weight.

*OpenAPI Specs.*
These are very verbose, but relatively precise and clear. They can support everything the Kubernetes API supports (like validators) and we don't need to invent anything.

```yaml
spec:
  aStringProp:
    type: string
    description: Another super helpful description.

  required: [aStringProp]
```

*Kro's Simple Schema*
We could take the approach [Kro used with Simple Schema](https://kro.run/docs/concepts/simple-schema/). That approach seems fairly clean, but it is stringly-typed. Perhaps that can be mitigated within the language server. It would require inventing and documenting a syntax, and at some point you'd still have to defer to CRDs directly (like arrays of custom objects with specific structure).

```yaml
spec:
  aStringProp: string | required=true, description="Another super helpful description."
```

*Hybrid Approach*
We could implement something that allows very simple structures to be easily defined, but also allows a fully OpenAPI block. We might be able to do this by disallowing properties named `type` and using that as the OpenAPI indicator.

```yaml
spec:
  aStringProp: string

  anArrayOfThings:
    type: array
    description: An array of objects with a specific structure.
    minItems: 2
    maxItems: 2
    items:
      type: object
      description: An object that defines a person.
      properties:
        name: string
        age: integer
      required: [name, age]

  required: [aStringProp, anArrayOfThings]
```

I don't think this buys much in a lot of cases, but that would let you make very simple schemas quickly and easily then switch to the full OpenAPI approach once the design is solidified?
