### ISSUE TITLE
ResourceFunction issues with Cluster scoped resources despite `namespaced: false`

### ISSUE THREAD

**Issue by jmcclell** [koreo-dev/koreo-core#26]
Generating a cluster-scoped resource with a ResourceFunction causes unit tests to fail and the controller to continuously attempt to sync.

Unit tests can be forced to pass by adding a `namespace: ~` to the expected output, but this doesn't solve the controller sync issue. This is problematic in workflows where the output of the resource creation is used in subsequent steps—it never seems to proceed? Strangely, the UI both shows issues _and_ a healthy state.

Here's an example where I'm trying to create a Kargo Project, which are cluster scoped resources.

```
apiVersion: koreo.dev/v1beta1
kind: ResourceFunction
metadata:
  name: customservice-definition-kargo-project.v1
spec:
  apiConfig:
    apiVersion: kargo.akuity.io/v1alpha1
    kind: Project
    name: =inputs.name
    namespaced: false
  resource:
    spec: ~
---
apiVersion: koreo.dev/v1beta1
kind: FunctionTest
metadata:
  name: customservice-definition-kargo-project-test.v1
spec:
  functionRef:
    kind: ResourceFunction
    name: customservice-definition-kargo-project.v1
  inputs:
      name: test
  testCases:
    - label: renders Kargo Project from inputs
      expectResource:
        apiVersion: kargo.akuity.io/v1alpha1
        kind: Project
        metadata:
          name: test
        spec:
          description: "Kargo project for test"
```

The unit tests will show as failing here. Adding `namespace: ~` to the `expectedOutput` silences the failure.

The Koreo UI will show the following

![Image](https://github.com/user-attachments/assets/d24f3d63-1e40-4cd0-9eec-a1750277c353)

The workflow step has a warning, but the status from the Kargo project reports as healthy.

Likewise, in the instance view, it will continuously show reconcilation  issues over the missing namespace field:

![Image](https://github.com/user-attachments/assets/cfc9639c-4128-4f15-8920-da1fc6f476a1)

Also, side note: this particular CRD (Kargo's `Project`) doesn't require a body at all outside of metadata. However, ResourceFunction _requires_ that `resource` be a non-empty object. Not a big deal in this case as I can use an empty `spec:` since the CRD does have spec as an optional field, but there may be other cases where metadata-only CRDs exist and don't have this?
